create table address (id bigint generated by default as identity, country varchar(2) not null, locality varchar(255), post_office_box_number varchar(255), postal_code varchar(255), region varchar(255), street_address varchar(255) not null, primary key (id))
create table job (id bigint generated by default as identity, created timestamp not null, amount decimal(19,2), currency varchar(3), resource_id binary not null, start_date_time timestamp, type varchar(255), customer_id bigint, primary key (id))
create table person (id bigint generated by default as identity, created timestamp not null, family_name varchar(255), given_name varchar(255), phone_number varchar(255) not null, resource_id binary not null, address_id bigint, primary key (id))
alter table job add constraint UK_e6nytqto8v0g06sjwf6ecj9g9 unique (resource_id)
alter table person add constraint UK_ja8diba20mpeofr4nk33hnksj unique (resource_id)
alter table job add constraint FKpecpeaj5e1s6vfh5pw6h9khnc foreign key (customer_id) references person
alter table person add constraint FKk7rgn6djxsv2j2bv1mvuxd4m9 foreign key (address_id) references address
