spring:
  datasource:
    url: "jdbc:h2:mem:i18n_book;COLLATION=ICU4J_en_US"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
logging:
  level:
    org:
      hibernate:
        tool:
          hbm2ddl: DEBUG
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG