
CREATE TABLE address
  ( 
     id                     BIGINT GENERATED BY DEFAULT AS IDENTITY, 
     country                VARCHAR(2) NOT NULL, 
     locality               VARCHAR(255), 
     post_office_box_number VARCHAR(255), 
     postal_code            VARCHAR(255), 
     region                 VARCHAR(255), 
     street_address         VARCHAR(255) NOT NULL, 
     PRIMARY KEY (id) 
  );

CREATE TABLE person
  (
     id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
     created         TIMESTAMP NOT NULL,
     family_name  VARCHAR(255),
     given_name   VARCHAR(255),
     phone_number VARCHAR(255) NOT NULL,
     resource_id  UUID NOT NULL,
     address_id   BIGINT,
     PRIMARY KEY (id),
     FOREIGN KEY (address_id) REFERENCES
       address
  );

CREATE TABLE job 
  ( 
     id              BIGINT GENERATED BY DEFAULT AS IDENTITY, 
     created         TIMESTAMP NOT NULL, 
     amount          DECIMAL(19, 2), 
     currency        VARCHAR(3), 
     resource_id     UUID NOT NULL,
     start_date_time TIMESTAMP, 
     type            VARCHAR(255),
     customer_id     BIGINT, 
     PRIMARY KEY (id),
     FOREIGN KEY (customer_id)
       REFERENCES person
  ); 

